export const GET_PROFILE_INFO = "GET_PROFILE_INFO"
export const GET_ERROR = "GET_ERROR"

export const TOGGLE_LIKE_POST_SUCCESS = "TOGGLE_LIKE_POST_SUCCESS"

export const LOGIN = "LOGIN"
export const LOGIN_ERROR = "LOGIN_ERROR"
export const LOGIN_CHECK = "LOGIN_CHECK"
