export const GET_BLOG_LIST = "GET_BLOG_LIST"
export const GET_BLOG_DETAIL = "GET_BLOG_DETAIL"

export const POST_NEW_POST_SUCCESS = "POST_NEW_POST_SUCCESS"
export const POST_COMMENT_SUCCESS = "POST_COMMENT_SUCCESS"

export const DELETE_POST_SUCCESS = "DELETE_POST_SUCCESS"

export const UPDATE_POST_SUCCESS = "UPDATE_POST_SUCCESS"

export const CHANGE_NEW_POST_STATE= "CHANGE_NEW_POST_STATE"

export const CHANGE_NEW_COMMENT_STATE= "CHANGE_NEW_COMMENT_STATE"

export const GET_ERROR = "GET_ERROR"

export const TOGGLE_LIKE_POST_SUCCESS = "TOGGLE_LIKE_POST_SUCCESS"




